### ISSUE TITLE
Docker image not found when running `make run`

### ISSUE THREAD

**Issue by sargue** [dyne/fabchain#7]
Running `make run` tries to pull a docker image using a tag built from a hash and a version string. They appear to be out of sync currently as the version says 0.7.0 and the hash `516fe1f1f82d1114ffb03fd9cd8d4a14100b64de` which points to an unpublished version.

```
Unable to find image 'dyne/dyneth:0.7.0-516fe1f1f82d1114ffb03fd9cd8d4a14100b64de' locally
docker: Error response from daemon: manifest for dyne/dyneth:0.7.0-516fe1f1f82d1114ffb03fd9cd8d4a14100b64de not found: manifest unknown: manifest unknown.
```

Reverting the version string to 0.6.0 allows the script to run.

**Comment by jaromil** [comment]
@sargue hi @sargue! sorry for the mistake, forgot to build and push after last container modification. The updated docker image is now online. To run a local node you will also need the genesis and bootnodes files... we are automating the download

**Comment by jaromil** [comment]
@sargue for the image to run correctly you need also to pull commit dfe2999 which initializes the genesis and bootnodes
